# docker network create phpinfo-network
networks:
  phpinfo-network:
    
# docker run --detach --name phpinfo --network phpinfo-network --publish 80:8080 --restart always academiaonline/simplilearn-phpinfo:latest
services:
  phpinfo:
    deploy:
      placement:
        constraints:
        - node.role == worker
      restart_policy:
        condition: any
    image: academiaonline/simplilearn-phpinfo:latest
    networks:
      - phpinfo-network
    ports:
      - 80:8080
      
version: '3.8'     
